logging:
  level:
    ROOT: INFO
    com.potato112.springdemo: DEBUG
    org.springframework.test: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: ../../log/debug.log
