version: '2'
services:
  trade-db:
    container_name: "demo-db"
    image: mysql
    environment:
      - "MYSQL_DATABASE=demo-db"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root"
    expose:
      - "33060"
    ports:
      - "33060:3306"
    networks:
      - trade_network

networks:
  trade_network:
    driver: bridge